name: "test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ./
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        target_repo_url: git@github.com:net-engine/github-repository-sync-action-test.git
